export const SCENES = {
	BOOT: 'BOOT_SCENE_KEY',
	GAME: 'GAME_SCENE_KEY',
	LOGIN: 'LOGIN_SCENE_KEY',
	REGISTER: 'REGISTER_SCENE_KEY',
	MENU: 'MENU_SCENE_KEY',
}
export const SPRITES = {
	PADDLE: "PADDLE_SPRITE_KEY",
	BALL: "BALL_SPRITE_KEY",
	BACKGROUND: "BACKGROUND_SPRITE_KEY"
}

export const HTML = {
	REGISTER: "REGISTER_HTML_KEY",
	LOGIN: "LOGIN_HTML_KEY"
}
export const ANIMATION = {
	BALL: "BALL_ANIMATION_KEY"
}
export const CONFIG = {
	WIDTH: 800,
	HEIGHT: 600

}